version: '3.1'

services:


  db:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: 'agmatix'
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    expose: 
      - '6603'

  etl:
    container_name: etl
    build: .
    environment: 
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    depends_on: 
      - db
    links:
      - db